//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Riipen_SSD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriteriaScore
    {
        public int Id { get; set; }
        public int TeamId { get; set; }
        public int CriteriaId { get; set; }
        public int ContestId { get; set; }
        public Nullable<int> Score { get; set; }
        public string Comment { get; set; }
        public bool PubliclyViewable { get; set; }
        public string Judge_ID { get; set; }
        public bool Submitted { get; set; }
    
        public virtual Criterion Criterion { get; set; }
        public virtual Team Team { get; set; }
    }
}
